### PR TITLE
FAB-17777 Create basic settings.yaml

### PR DESCRIPTION
**Pull request by ryjones**
This represents the current settings of this repo.

Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by ryjones** [comment]
blocked by https://github.com/hyperledger/fabric-ca/pull/138

**Comment by btl5037** [comment]
You'll need to add an entry here in this PR to ignore this file: https://github.com/hyperledger/fabric-ca/blob/master/scripts/check_license#L15

**Comment by btl5037** [comment]
You'll also need to rebase now to pick up the CI change

**Pull request merged**
