### PR TITLE
[Documentation update]Update configtx.rst

### PR DESCRIPTION
**Pull request by xiayanzheng**
fix following issue after run `configtxgen -profile OrgsOrdererGenesis -outputBlock /tmp/hyperledger/org0/orderer/genesis.block -channelID syschannel` by fix format.
* 'Organizations[0]' has invalid keys: OrdererEndpoints
* 'Profiles[TwoOrgsOrdererGenesis].Orderer.Organizations[0]' has invalid keys: OrdererEndpoints
* Profiles[TwoOrgsOrdererGenesis].Orderer.Organizations[0]' has invalid keys: OrdererEndpoints [recovered]
* 'Profiles[TwoOrgsOrdererGenesis].Orderer.Organizations[0]' has invalid keys: OrdererEndpoints
* Error reading configuration: While parsing config: yaml: line 85: mapping values are not allowed in this context
* '' has invalid keys: orgschannel, orgsorderergenesis
* 'Profiles[OrgsOrdererGenesis].Consortiums[Organizations]' expected a map, got 'slice'

Signed-off-by: LF <xiayanzheng@outlook.com>

#### Type of change

- Documentation update

### CODE REVIEW

**Comment by xiayanzheng** [comment]
add `GODEBUG=netdns=go` to peer1-org1  and peer2-org1's environment variables to fix following issue
2022-12-16 10:19:04.262 UTC [grpc] HandleSubConnStateChange -> DEBU 01a pickfirstBalancer: HandleSubConnStateChange: 0xc00214c9b0, CONNECTING
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f877852d259]

**Comment by jkneubuh** [comment]
Hi @xiayanzheng - in which build of Fabric-CA did you encounter the SIGSEGV?

There have been some recent changes in support of the arm64 chipset, it's possible this is a regression.  If so, we should fix this in the build, not with a docs workaround.   How / where did you encounter the error?

**Comment by xiayanzheng** [comment]
> Hi @xiayanzheng - in which build of Fabric-CA did you encounter the SIGSEGV?
> 
> There have been some recent changes in support of the arm64 chipset, it's possible this is a regression. If so, we should fix this in the build, not with a docs workaround. How / where did you encounter the error?

Hi @jkneubuh I encountered this issue in ‘hyperledger/fabric-peer 1.4.0 imageID: 304fac59b501‘.
I was trying to follow this [guide](https://hyperledger-fabric-ca.readthedocs.io/en/latest/operations_guide.html#launch-org1-s-peers)  to bring up peers for both org1 and org2, both org's peer1 was successfully up and running without issue, but when I launching peer2 for both org, the error showed up, after I add `GODEBUG=netdns=go` environment variable for both org‘s peer2 the error disappeared.

**Comment by denyeart** [comment]
If there is an issue with peer please report to https://github.com/hyperledger/fabric/issues , note that v1.4.0 is very outdated and not maintained, it would be good to know if the problem exists with v2.x peers.

**Pull request closed without merging**
