### PR TITLE
Remove outdated setup functions for gerrit

### PR DESCRIPTION
**Pull request by sykesm**
`scripts/bash_profile` contained a bunch of gerrit helpers that are no longer needed so remove it.

### CODE REVIEW

**Comment by btl5037** [comment]
The AZP outage is over, looks like I'll probably need you to force-push to reset and re-establish to the webhooks. Sorry for the trouble

**Comment by btl5037** [comment]
I opened a support ticket on this issue with Microsoft

**Comment by sykesm** [comment]
> I opened a support ticket on this issue with Microsoft

I'm pretty sure it's going to be related to the fact that the azp configuration has overlapping triggers on release-1.4 and master.

**Comment by btl5037** [comment]
Removing the conflicting trigger seems to have worked

**Pull request merged**
